apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ezio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ezio
    app.kubernetes.io/part-of: ci10t-786-0073-app
  name: devfile-sample-ezio
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ezio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ezio
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0073-tenant/ci10t-786-0073-app/devfile-sample-ezio@sha256:59f04b983c334a07997e28b194c8b25267cb5e110877bc6be7f73a5775de01f6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
